#!/bin/awk

BEGIN {FS="[^(A-Z|^)]*"}

#$1 != " " {for(i=1; i<=NF; i++){arr[NR, i] = $i;}}
$1 != " " {for(i=1; i<=NF; i++){printf $i "X";} printf " " i " " NF " " NR "\n"}

length($0) == 0 {
#  for(i in arr){
#    print i
#    for(ii in arr[i]){
#      printf arr[i][ii]
#    }
#    print ""
#  }

#  for(combined in arr){
#    split(combined, id, SUBSEP)
#    printf id[1] " " id[2] " " arr[id[1], id[2]] "\n"
#  }

# print length(arr)

}

length($0) == 0 {exit}

length($0) == 0 {FS=" "}

$1 == "move" {print $2 $4 $6}
