name: verify_solutions

on:
  push:
  workflow_dispatch:

jobs:
  verify solutions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: run
        run: |
          ls
